"""Turns protocol/test-vectors/*.json into a C++ include for test_kinjo.cpp.

Usage: python3 gen_vectors_inc.py OUT_FILE
"""

import json
import sys
from pathlib import Path

VECTORS = Path(__file__).resolve().parents[2] / "protocol" / "test-vectors"


def load(name):
    return json.loads((VECTORS / name).read_text())


def s(v):
    return json.dumps(v)


def strs(items):
    return "{" + ", ".join(s(i) for i in items) + "}"


def strokes(v):
    return "{" + ", ".join("{" + ", ".join(f"{{{x}, {y}}}" for x, y in st) + "}" for st in v) + "}"


def main(out_path):
    lines = ["// Generated by gen_vectors_inc.py from protocol/test-vectors. Do not edit.", ""]

    lines.append("static const HeaderCase HEADER_CASES[] = {")
    for c in load("header.json")["cases"]:
        f = c["fields"]
        lines.append(f"  {{{f['version']}, {f['type']}, {f['flags']}, {f['ttl']}, {f['message_id']}u, {f['source']}u, "
                     f"{f['destination']}u, {f['frag_index']}, {f['frag_count']}, {s(c['header'])}, {s(c['ad'])}}},")
    lines.append("};")

    lines.append("static const std::vector<FragmentCase> FRAGMENT_CASES = {")
    for c in load("fragment.json")["cases"]:
        lines.append(f"  {{{c['type']}, {c['message_id']}u, {c['source']}u, {c['destination']}u, {c['ttl']}, "
                     f"{s(c['body'])}, {strs(c['packets'])}}},")
    lines.append("};")

    k = load("keys.json")
    for who in ("handheld", "laptop"):
        lines.append(f"static const char* {who.upper()}_PRIV = {s(k[who]['private'])};")
        lines.append(f"static const char* {who.upper()}_PUB = {s(k[who]['public'])};")
        lines.append(f"static const uint32_t {who.upper()}_NODE_ID = {k[who]['node_id']}u;")
    lines.append(f"static const char* SHARED_KEY = {s(k['key'])};")

    lines.append("static const std::vector<SealedCase> SEALED_CASES = {")
    for c in load("sealed.json")["cases"]:
        lines.append(f"  {{{s(c['label'])}, {s(c['key'])}, {c['source']}u, {c['destination']}u, {c['message_id']}u, "
                     f"{c['ttl']}, {s(c['nonce'])}, {s(c['plaintext'])}, {strs(c['packets'])}}},")
    lines.append("};")

    lines.append("static const std::vector<DrawingCase> DRAWING_CASES = {")
    for c in load("drawing.json")["cases"]:
        ints = lambda v: "{" + ", ".join(str(x) for x in v) + "}"
        lines.append(f"  {{{strokes(c['strokes'])}, {ints(c['colors'])}, {s(c['plaintext'])}, {strokes(c['decoded'])}, "
                     f"{ints(c['decoded_colors'])}}},")
    lines.append("};")

    lines.append("static const std::vector<NoteCase> NOTE_CASES = {")
    for c in load("drawing.json")["notes"]:
        ints = lambda v: "{" + ", ".join(str(x) for x in v) + "}"
        lines.append(f"  {{{s(c['text'])}, {s(c['plaintext'])}, {strokes(c['decoded'])}, {ints(c['decoded_colors'])}}},")
    lines.append("};")

    i = load("identity.json")
    lines.append(f"static const IdentityCase IDENTITY = {{{s(i['public'])}, {s(i['name'])}, {s(i['body'])}, "
                 f"{strs(i['packets'])}}};")

    c = load("cobs.json")
    lines.append("static const std::vector<CobsCase> COBS_CASES = {")
    lines += [f"  {{{s(x['raw'])}, {s(x['encoded'])}}}," for x in c["cases"]]
    lines.append("};")
    lines.append("static const std::vector<CobsCase> COBS_DECODE_ONLY = {")
    lines += [f"  {{{s(x['raw'])}, {s(x['encoded'])}}}," for x in c["decode_only"]]
    lines.append("};")
    f = c["serial_frame"]
    lines.append(f"static const SerialFrameCase SERIAL_FRAME = {{{f['frame_type']}, {s(f['body'])}, {s(f['wire'])}}};")

    p = load("provision.json")
    lines.append("static const std::vector<ProvisionCase> PROVISION_REQUESTS = {")
    lines += [f"  {{{s(r['label'])}, {s(r['body'])}}}," for r in p["requests"]]
    lines.append("};")
    lines.append("static const std::vector<ProvisionCase> PROVISION_REPLIES = {")
    lines += [f"  {{{s(r['label'])}, {s(r['body'])}}}," for r in p["replies"]]
    lines.append("};")
    lines.append("static const std::vector<ProvisionCase> PROVISION_MALFORMED = {")
    lines += [f"  {{{s(m['label'])}, {s(m['body'])}}}," for m in p["malformed"]]
    lines.append("};")

    u = load("contact-update.json")
    lines.append("static const std::vector<UpdateCase> UPDATE_CASES = {")
    lines += [f"  {{{s(c['label'])}, {c['op']}, {c['flags']}, {s(c['pub'])}, {s(c['name'])}, {s(c['plaintext'])}}},"
              for c in u["cases"]]
    lines.append("};")
    lines.append("static const std::vector<ProvisionCase> UPDATE_MALFORMED_CASES = {")
    lines += [f"  {{{s(m['label'])}, {s(m['plaintext'])}}}," for m in u["malformed"]]
    lines.append("};")
    lines.append("static const std::vector<AcceptCase> UPDATE_ACCEPT = {")
    lines += [f"  {{{s(a['label'])}, {s(a['own'])}, {s(a['sender'])}, {s(a['target'])}, {str(a['accepted']).lower()}}},"
              for a in u["accept"]]
    lines.append("};")
    c = u["sealed"]
    lines.append(f"static const SealedCase UPDATE_SEALED = {{\"contact_update\", {s(c['key'])}, {c['source']}u, "
                 f"{c['destination']}u, {c['message_id']}u, {c['ttl']}, {s(c['nonce'])}, {s(c['plaintext'])}, "
                 f"{strs(c['packets'])}}};")

    Path(out_path).write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
