[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["dependencies"]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[soldeer]
remappings_generate = true
remappings_regenerate = true
remappings_location = "txt"
recursive_deps = false
